name: Run Selfbot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        # Pin discord.py to 1.7.3
        run: pip install discord.py==1.7.3

      - name: Run bot
        run: python selfbot.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
